### ISSUE TITLE
Can't reproduce training - openseg clip model not working

### ISSUE THREAD

**Issue by lusxvr** [opennerf/opennerf#4]
Great work, I was super intruiged by the paper and wanted to reproduce the method for a university project.  
Unfortunately I cannot get it to run following the steps from the README, no matter if I try on Google Colab or on a standalone VM.   
This is my errors, it is related to some kind of openseg clip model (?) and I cannot figure out how to solve it unfortunately.   
Like I said, it occurs regardless of if I try it on Colab or on a standalone VM.   
The installation of the environment and of the dependencies ran through.  
Do I need to manually download some clip checkpoints?

### Error during training:
```
(opennerf) ubuntu@ip-172-31-37-8:~/adl4vc/opennerf$ ns-train opennerf --data /home/ubuntu/adl4vc/data/nerfstudio_/replica_office0
2024-05-15 11:09:49.483899: I tensorflow/core/util/port.cc:113] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2024-05-15 11:09:49.544300: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F AVX512_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-05-15 11:09:50.425251: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
[11:09:59] Using --data alias for --data.pipeline.datamanager.data                                          train.py:230
──────────────────────────────────────────────────────── Config ────────────────────────────────────────────────────────
TrainerConfig(
    _target=<class 'nerfstudio.engine.trainer.Trainer'>,
    output_dir=PosixPath('outputs'),
    method_name='opennerf',
    experiment_name=None,
    project_name='nerfstudio-project',
    timestamp='2024-05-15_110959',
    machine=MachineConfig(seed=42, num_devices=1, num_machines=1, machine_rank=0, dist_url='auto', device_type='cuda'),
    logging=LoggingConfig(
        relative_log_dir=PosixPath('.'),
        steps_per_log=10,
        max_buffer_size=20,
        local_writer=LocalWriterConfig(
            _target=<class 'nerfstudio.utils.writer.LocalWriter'>,
            enable=True,
            stats_to_track=(
                <EventName.ITER_TRAIN_TIME: 'Train Iter (time)'>,
                <EventName.TRAIN_RAYS_PER_SEC: 'Train Rays / Sec'>,
                <EventName.CURR_TEST_PSNR: 'Test PSNR'>,
                <EventName.VIS_RAYS_PER_SEC: 'Vis Rays / Sec'>,
                <EventName.TEST_RAYS_PER_SEC: 'Test Rays / Sec'>,
                <EventName.ETA: 'ETA (time)'>
            ),
            max_log_size=10
        ),
        profiler='basic'
    ),
    viewer=ViewerConfig(
        relative_log_filename='viewer_log_filename.txt',
        websocket_port=None,
        websocket_port_default=7007,
        websocket_host='0.0.0.0',
        num_rays_per_chunk=32768,
        max_num_display_images=512,
        quit_on_train_completion=False,
        image_format='jpeg',
        jpeg_quality=75,
        make_share_url=False,
        camera_frustum_scale=0.1,
        default_composite_depth=True
    ),
    pipeline=OpenNerfPipelineConfig(
        _target=<class 'opennerf.opennerf_pipeline.OpenNerfPipeline'>,
        datamanager=OpenNerfDataManagerConfig(
            _target=<class 'opennerf.opennerf_datamanager.OpenNerfDataManager'>,
            data=PosixPath('/home/ubuntu/adl4vc/data/nerfstudio_/replica_office0'),
            masks_on_gpu=False,
            images_on_gpu=False,
            dataparser=NerfstudioDataParserConfig(
                _target=<class 'nerfstudio.data.dataparsers.nerfstudio_dataparser.Nerfstudio'>,
                data=PosixPath('.'),
                scale_factor=1.0,
                downscale_factor=None,
                scene_scale=1.0,
                orientation_method='up',
                center_method='poses',
                auto_scale_poses=True,
                eval_mode='fraction',
                train_split_fraction=0.99,
                eval_interval=8,
                depth_unit_scale_factor=0.001,
                mask_color=None,
                load_3D_points=False
            ),
            train_num_rays_per_batch=4096,
            train_num_images_to_sample_from=-1,
            train_num_times_to_repeat_images=-1,
            eval_num_rays_per_batch=4096,
            eval_num_images_to_sample_from=-1,
            eval_num_times_to_repeat_images=-1,
            eval_image_indices=(0,),
            collate_fn=<function nerfstudio_collate at 0x7f08d4de0550>,
            camera_res_scale_factor=1.0,
            patch_size=1,
            camera_optimizer=None,
            pixel_sampler=PixelSamplerConfig(
                _target=<class 'nerfstudio.data.pixel_samplers.PixelSampler'>,
                num_rays_per_batch=4096,
                keep_full_image=False,
                is_equirectangular=False,
                ignore_mask=False,
                fisheye_crop_radius=None,
                rejection_sample_mask=True,
                max_num_iterations=100
            ),
            patch_tile_size_range=(0.05, 0.5),
            patch_tile_size_res=7,
            patch_stride_scaler=0.5
        ),
        model=OpenNerfModelConfig(
            _target=<class 'opennerf.opennerf_model.OpenNerfModel'>,
            enable_collider=True,
            collider_params={'near_plane': 2.0, 'far_plane': 6.0},
            loss_coefficients={'rgb_loss_coarse': 1.0, 'rgb_loss_fine': 1.0},
            eval_num_rays_per_chunk=32768,
            prompt=None,
            near_plane=0.05,
            far_plane=1000.0,
            background_color='last_sample',
            hidden_dim=64,
            hidden_dim_color=64,
            hidden_dim_transient=64,
            num_levels=16,
            base_res=16,
            max_res=2048,
            log2_hashmap_size=19,
            features_per_level=2,
            num_proposal_samples_per_ray=(256, 96),
            num_nerf_samples_per_ray=48,
            proposal_update_every=5,
            proposal_warmup=5000,
            num_proposal_iterations=2,
            use_same_proposal_network=False,
            proposal_net_args_list=[
                {'hidden_dim': 16, 'log2_hashmap_size': 17, 'num_levels': 5, 'max_res': 128, 'use_linear': False},
                {'hidden_dim': 16, 'log2_hashmap_size': 17, 'num_levels': 5, 'max_res': 256, 'use_linear': False}
            ],
            proposal_initial_sampler='piecewise',
            interlevel_loss_mult=1.0,
            distortion_loss_mult=0.002,
            orientation_loss_mult=0.0001,
            pred_normal_loss_mult=0.001,
            use_proposal_weight_anneal=True,
            use_appearance_embedding=True,
            use_average_appearance_embedding=True,
            proposal_weights_anneal_slope=10.0,
            proposal_weights_anneal_max_num_iters=1000,
            use_single_jitter=True,
            predict_normals=False,
            disable_scene_contraction=False,
            use_gradient_scaling=False,
            implementation='tcnn',
            appearance_embed_dim=32,
            average_init_density=1.0,
            camera_optimizer=CameraOptimizerConfig(
                _target=<class 'nerfstudio.cameras.camera_optimizers.CameraOptimizer'>,
                mode='SO3xR3',
                trans_l2_penalty=0.01,
                rot_l2_penalty=0.001,
                optimizer=None,
                scheduler=None
            ),
            clip_loss_weight=0.1,
            dino_loss_weight=0.0,
            openseg_loss_weight=1.0,
            openseg_loss='MSE',
            n_scales=30,
            max_scale=1.5,
            num_opennerf_samples=24,
            hashgrid_layers=(12, 12),
            hashgrid_resolutions=((16, 128), (128, 512)),
            hashgrid_sizes=(19, 19),
            num_hidden_clip_layers=1
        ),
        network=BaseImageEncoderConfig(_target=<class 'opennerf.encoders.image_encoder.BaseImageEncoder'>)
    ),
    optimizers={
        'proposal_networks': {
            'optimizer': AdamOptimizerConfig(
                _target=<class 'torch.optim.adam.Adam'>,
                lr=0.01,
                eps=1e-15,
                max_norm=None,
                weight_decay=0
            ),
            'scheduler': None
        },
        'fields': {
            'optimizer': RAdamOptimizerConfig(
                _target=<class 'torch.optim.radam.RAdam'>,
                lr=0.01,
                eps=1e-15,
                max_norm=None,
                weight_decay=0
            ),
            'scheduler': ExponentialDecaySchedulerConfig(
                _target=<class 'nerfstudio.engine.schedulers.ExponentialDecayScheduler'>,
                lr_pre_warmup=1e-08,
                lr_final=0.001,
                warmup_steps=0,
                max_steps=30000,
                ramp='cosine'
            )
        },
        'opennerf': {
            'optimizer': RAdamOptimizerConfig(
                _target=<class 'torch.optim.radam.RAdam'>,
                lr=0.01,
                eps=1e-15,
                max_norm=None,
                weight_decay=1e-09
            ),
            'scheduler': ExponentialDecaySchedulerConfig(
                _target=<class 'nerfstudio.engine.schedulers.ExponentialDecayScheduler'>,
                lr_pre_warmup=1e-08,
                lr_final=0.001,
                warmup_steps=0,
                max_steps=4000,
                ramp='cosine'
            )
        }
    },
    vis='viewer',
    data=PosixPath('/home/ubuntu/adl4vc/data/nerfstudio_/replica_office0'),
    prompt=None,
    relative_model_dir=PosixPath('nerfstudio_models'),
    load_scheduler=True,
    steps_per_save=2000,
    steps_per_eval_batch=500,
    steps_per_eval_image=500,
    steps_per_eval_all_images=25000,
    max_num_iterations=30000,
    mixed_precision=True,
    use_grad_scaler=False,
    save_only_latest_checkpoint=True,
    load_dir=None,
    load_step=None,
    load_config=None,
    load_checkpoint=None,
    log_gradients=False,
    gradient_accumulation_steps={}
)
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
           Saving config to: outputs/replica_office0/opennerf/2024-05-15_110959/config.yml      experiment_config.py:136
           Saving checkpoints to: outputs/replica_office0/opennerf/2024-05-15_110959/nerfstudio_models    trainer.py:137
           Auto image downscale factor of 1                                                 nerfstudio_dataparser.py:484
Setting up training dataset...
Caching all 198 images.
Setting up evaluation dataset...
Caching all 2 images.
Traceback (most recent call last):
  File "/home/ubuntu/adl4vc/opennerf/opennerf/data/utils/feature_dataloader.py", line 53, in try_load
    self.load()
  File "/home/ubuntu/adl4vc/opennerf/opennerf/data/utils/feature_dataloader.py", line 37, in load
    raise FileNotFoundError
FileNotFoundError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/opennerf/bin/ns-train", line 8, in <module>
    sys.exit(entrypoint())
  File "/home/ubuntu/anaconda3/envs/opennerf/lib/python3.10/site-packages/nerfstudio/scripts/train.py", line 262, in entrypoint
    main(
  File "/home/ubuntu/anaconda3/envs/opennerf/lib/python3.10/site-packages/nerfstudio/scripts/train.py", line 247, in main
    launch(
  File "/home/ubuntu/anaconda3/envs/opennerf/lib/python3.10/site-packages/nerfstudio/scripts/train.py", line 189, in launch
    main_func(local_rank=0, world_size=world_size, config=config)
  File "/home/ubuntu/anaconda3/envs/opennerf/lib/python3.10/site-packages/nerfstudio/scripts/train.py", line 99, in train_loop
    trainer.setup()
  File "/home/ubuntu/anaconda3/envs/opennerf/lib/python3.10/site-packages/nerfstudio/engine/trainer.py", line 153, in setup
    self.pipeline = self.config.pipeline.setup(
  File "/home/ubuntu/anaconda3/envs/opennerf/lib/python3.10/site-packages/nerfstudio/configs/base_config.py", line 54, in setup
    return self._target(self, **kwargs)
  File "/home/ubuntu/adl4vc/opennerf/opennerf/opennerf_pipeline.py", line 46, in __init__
    self.datamanager: OpenNerfDataManager = config.datamanager.setup(
  File "/home/ubuntu/anaconda3/envs/opennerf/lib/python3.10/site-packages/nerfstudio/configs/base_config.py", line 54, in setup
    return self._target(self, **kwargs)
  File "/home/ubuntu/adl4vc/opennerf/opennerf/opennerf_datamanager.py", line 90, in __init__
    self.openseg_dataloader = OpenSegDataloader(
  File "/home/ubuntu/adl4vc/opennerf/opennerf/data/utils/openseg_dataloader.py", line 23, in __init__
    super().__init__(cfg, device, image_list, cache_path)
  File "/home/ubuntu/adl4vc/opennerf/opennerf/data/utils/feature_dataloader.py", line 23, in __init__
    self.try_load(image_list) # don't save image_list, avoid duplicates
  File "/home/ubuntu/adl4vc/opennerf/opennerf/data/utils/feature_dataloader.py", line 55, in try_load
    self.create(img_list)
  File "/home/ubuntu/adl4vc/opennerf/opennerf/data/utils/openseg_dataloader.py", line 31, in create
    openseg_model = tf2.saved_model.load(saved_model_path, tags=[tf.saved_model.tag_constants.SERVING],)
  File "/home/ubuntu/anaconda3/envs/opennerf/lib/python3.10/site-packages/tensorflow/python/saved_model/load.py", line 912, in load
    result = load_partial(export_dir, None, tags, options)["root"]
  File "/home/ubuntu/anaconda3/envs/opennerf/lib/python3.10/site-packages/tensorflow/python/saved_model/load.py", line 1016, in load_partial
    loader_impl.parse_saved_model_with_debug_info(export_dir))
  File "/home/ubuntu/anaconda3/envs/opennerf/lib/python3.10/site-packages/tensorflow/python/saved_model/loader_impl.py", line 59, in parse_saved_model_with_debug_info
    saved_model = parse_saved_model(export_dir)
  File "/home/ubuntu/anaconda3/envs/opennerf/lib/python3.10/site-packages/tensorflow/python/saved_model/loader_impl.py", line 119, in parse_saved_model
    raise IOError(
OSError: SavedModel file does not exist at: /home/ubuntu/misc/openseg_exported_clip/{saved_model.pbtxt|saved_model.pb}
```

### Error during viewing: 
 
```
(opennerf) ubuntu@ip-172-31-37-8:~/adl4vc/opennerf$ ns-viewer --load-config /home/ubuntu/adl4vc/opennerf/outputs/replica_office0/opennerf/2024-05-15_093913/config.yml
2024-05-15 09:55:06.461952: I tensorflow/core/util/port.cc:113] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2024-05-15 09:55:06.517533: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F AVX512_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-05-15 09:55:07.417818: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
[09:55:15] Auto image downscale factor of 1                                                 nerfstudio_dataparser.py:484
Setting up training dataset...
Caching all 198 images.
Setting up evaluation dataset...
Caching all 2 images.
Traceback (most recent call last):
  File "/home/ubuntu/adl4vc/opennerf/opennerf/data/utils/feature_dataloader.py", line 53, in try_load
    self.load()
  File "/home/ubuntu/adl4vc/opennerf/opennerf/data/utils/feature_dataloader.py", line 37, in load
    raise FileNotFoundError
FileNotFoundError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/opennerf/bin/ns-viewer", line 8, in <module>
    sys.exit(entrypoint())
  File "/home/ubuntu/anaconda3/envs/opennerf/lib/python3.10/site-packages/nerfstudio/scripts/viewer/run_viewer.py", line 135, in entrypoint
    tyro.cli(tyro.conf.FlagConversionOff[RunViewer]).main()
  File "/home/ubuntu/anaconda3/envs/opennerf/lib/python3.10/site-packages/nerfstudio/scripts/viewer/run_viewer.py", line 63, in main
    config, pipeline, _, step = eval_setup(
  File "/home/ubuntu/anaconda3/envs/opennerf/lib/python3.10/site-packages/nerfstudio/utils/eval_utils.py", line 105, in eval_setup
    pipeline = config.pipeline.setup(device=device, test_mode=test_mode)
  File "/home/ubuntu/anaconda3/envs/opennerf/lib/python3.10/site-packages/nerfstudio/configs/base_config.py", line 54, in setup
    return self._target(self, **kwargs)
  File "/home/ubuntu/adl4vc/opennerf/opennerf/opennerf_pipeline.py", line 46, in __init__
    self.datamanager: OpenNerfDataManager = config.datamanager.setup(
  File "/home/ubuntu/anaconda3/envs/opennerf/lib/python3.10/site-packages/nerfstudio/configs/base_config.py", line 54, in setup
    return self._target(self, **kwargs)
  File "/home/ubuntu/adl4vc/opennerf/opennerf/opennerf_datamanager.py", line 90, in __init__
    self.openseg_dataloader = OpenSegDataloader(
  File "/home/ubuntu/adl4vc/opennerf/opennerf/data/utils/openseg_dataloader.py", line 23, in __init__
    super().__init__(cfg, device, image_list, cache_path)
  File "/home/ubuntu/adl4vc/opennerf/opennerf/data/utils/feature_dataloader.py", line 23, in __init__
    self.try_load(image_list) # don't save image_list, avoid duplicates
  File "/home/ubuntu/adl4vc/opennerf/opennerf/data/utils/feature_dataloader.py", line 55, in try_load
    self.create(img_list)
  File "/home/ubuntu/adl4vc/opennerf/opennerf/data/utils/openseg_dataloader.py", line 31, in create
    openseg_model = tf2.saved_model.load(saved_model_path, tags=[tf.saved_model.tag_constants.SERVING],)
  File "/home/ubuntu/anaconda3/envs/opennerf/lib/python3.10/site-packages/tensorflow/python/saved_model/load.py", line 912, in load
    result = load_partial(export_dir, None, tags, options)["root"]
  File "/home/ubuntu/anaconda3/envs/opennerf/lib/python3.10/site-packages/tensorflow/python/saved_model/load.py", line 1016, in load_partial
    loader_impl.parse_saved_model_with_debug_info(export_dir))
  File "/home/ubuntu/anaconda3/envs/opennerf/lib/python3.10/site-packages/tensorflow/python/saved_model/loader_impl.py", line 59, in parse_saved_model_with_debug_info
    saved_model = parse_saved_model(export_dir)
  File "/home/ubuntu/anaconda3/envs/opennerf/lib/python3.10/site-packages/tensorflow/python/saved_model/loader_impl.py", line 119, in parse_saved_model
    raise IOError(
OSError: SavedModel file does not exist at: /home/ubuntu/misc/openseg_exported_clip/{saved_model.pbtxt|saved_model.pb}
```

**Comment by lusxvr** [comment]
This error can be resolved by downloading the open seg model (https://github.com/tensorflow/tpu/tree/master/models/official/detection/projects/openseg) and modifying the path to your saved location in `opennerf/opennerf/data/utils/feature_dataloader.py`

**Comment by lusxvr** [comment]
Unfortunately, when I did this, the openseg loading is just killed without any error. Any ideas what this could be? I didnt find anything in the openseg issues unfortunately.
![image](https://github.com/opennerf/opennerf/assets/87134473/90405b77-c31f-4d42-a556-e722a5147cbb)
I only have this picture atm, but happy to reproduce if anyone has any idea.

**Comment by francisengelmann** [comment]
Thanks for reporting this! I updated the README to include instructions for downloading the OpenSeg model: 
https://github.com/opennerf/opennerf?tab=readme-ov-file#data-preparation-and-openseg-model

Please let me know if this makes any difference. Otherwise could it be that your GPU is too small to run OpenSeg? I'm currently running it on a Titan RTX (24GB).

**Comment by lusxvr** [comment]
I tried it on colab and a vm with both running a T4 (16GB), so it was propably just too small. I will try on a new vm with a A5000 with 24GB, hopefully that works

**Comment by francisengelmann** [comment]
Assuming it works now? Let me know if not - closing for now
